[tool.poetry]
name = "jdbot"
version = "0.1.0"
description = ""
authors = ["repl.it user <replituser@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = {extras = ["voice"], version = "^1.6"}
dnspython = "^2.0.0"
flask = "^1.1.2"
pymongo = "^3.11.2"
dblpy = "^0.4.0"
jishaku = "^1.20.0"
aioimgur = "^0.1.0"
wavelink = "^0.9.6"
image = "^1.5.33"
asuna-api = "^0.2.5"
vt-py = "^0.6.1"
"mystbin.py" = "^1.0.1"
vt = "^3.1.3"
discord-ext-menus = {git = "https://github.com/Rapptz/discord-ext-menus"}
google-api-python-client = "^1.12.8"
aPRAW = "^0.6.8-alpha.0"
sr-api = {git = "https://github.com/iDutchy/sr_api.git"}
async-cse = "^0.3.0"
discord-py-slash-command = "^1.0.9"
TenGiphPy = "^2.5.0"
aiogTTS = "^1.1.0"
motor = "^2.3.1"
emojis = "^0.6.0"
ordereddict = "^1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
