[tool.poetry]
name = "jdbot"
version = "0.1.0"
description = ""
authors = ["repl.it user <replituser@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = {extras = ["voice"], version = "^1.5.1"}
dnspython = "^2.0.0"
flask = "^1.1.2"
pymongo = "^3.11.2"
gTTS = "^2.2.1"
"mystbin.py" = "^1.0.1"
sr-api = "^1.1.3"
dblpy = "^0.4.0"
jishaku = "^1.20.0"
asuna-api = "^0.2.3.1"
aioimgur = "^0.1.0"
wavelink = "^0.9.6"
vt-py = "^0.6.1"
image = "^1.5.33"
vt = "^3.1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
