[tool.poetry]
name = "jdbot"
version = "0.1.0"
description = ""
authors = ["repl.it user <replituser@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
dnspython = "^2.1.0"
"discord.py" = {extras = ["voice"], version = "^1.7.1"}
Flask = "^1.1.2"
dblpy = "^0.4.0"
aioimgur = "^0.1.1"
wavelink = "^0.9.9"
image = "^1.5.33"
asuna-api = "^0.2.6"
vt-py = "^0.6.1"
google-api-python-client = "^2.2.0"
aPRAW = "^0.6.8-alpha.0"
async-cse = "^0.3.0"
discord-py-slash-command = "^1.1.2"
TenGiphPy = "^2.5.0"
aiogTTS = "^1.1.0"
motor = "^2.4.0"
emojis = "^0.6.0"
ordereddict = "^1.1"
asyncdagpi = "^3.3.2"
discord-ext-menus = {git = "https://github.com/Rapptz/discord-ext-menus"}
sr-api = {git = "https://github.com/iDutchy/sr_api"}
jishaku = {git = "https://github.com/Gorialis/jishaku.git"}
"mystbin.py" = "^2.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
